name = "BDDUtils"
uuid = "988fec45-2e65-4f7c-9ed6-bc7bd8ad251c"
authors = ["Adrien Banse"]
version = "1.0.0-DEV"

[deps]
CUDD = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
